# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: appocean_development
  pool: 5
  username: anders

production:
  host: ec2-107-22-171-63.compute-1.amazonaws.com
  adapter: postgresql
  encoding: unicode
  database: d6mde0uu42243f
  user: ksbrgoviyvepvs
  port: 5432
  password: ds5Xlc8tWqjCIa6-Ksxxk3-wfO
  pool: 5